#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MWF.Mobile.Android.Resource", IsApplication=true)]

namespace MWF.Mobile.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Chance.MvvmCross.Plugins.UserInteraction.Droid.Resource.String.library_name = global::MWF.Mobile.Android.Resource.String.library_name;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.ApplicationName = global::MWF.Mobile.Android.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.Hello = global::MWF.Mobile.Android.Resource.String.Hello;
			global::Splat.Resource.String.library_name = global::MWF.Mobile.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrowIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cross = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int empty_square = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_accept = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_error = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_overflow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_refresh = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_search = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_warning = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mwf_logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int proteoLogo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int tick = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int warning = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int SafetyCheckItem = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int SafetyCheckTitle = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int SafetyListView = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int action_refresh = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int action_search = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int button1 = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int buttonPasscode = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int button_done = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int checksdonebutton = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int donebutton = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int fragment_host = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int odometerText = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int signature_view = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int submit = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int trailerText = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Fragment_About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment_CustomerCode = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment_Manifest = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fragment_Odometer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_Passcode = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_SafetyCheckFaultView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Fragment_SafetyCheckSignature = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Fragment_TrailerSelectionView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Fragment_VehicleListView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Item_SafetyCheckItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Item_Trailer = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Item_Vehicle = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Page_Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Page_Startup = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SafetyCheckView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SplashScreen = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main_activity_actions = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int vehicle_activity_actions = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int action_refresh = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int action_search = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int action_settings = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int application_name = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Proteo = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int Proteo_Button = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Proteo_Button_Bottom = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Proteo_EditText = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int Proteo_EditText_NumberPasscode = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Proteo_ImageView_MWFLogo = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int Proteo_SignaturePad = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int Proteo_TextView_Information = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int Proteo_TextView_MainHeading = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Proteo_TextView_SubHeading = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int Proteo_TextView_SubInformation = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int ProteoNoMargins = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int Theme_Splash = 2131099660;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
